const products = [
    {
        id: 0,
        name:"Green Dog",
        price: 6900,
        desciption: "Green Dog, alimento 100% Vegetal!",
        imgSrc: "./Images/GD.PNG",
        Type: "Perros",
    },
    {
        id: 1,
        name:"ProPlan",
        price: 7000,
        desciption: "Proplan un clasico en alimentos",
        imgSrc: "./Images/Proplan.png",
        Type: "Perros",
    },
    {
        id: 2,
        name:"Royal Canin",
        price: 12000,
        desciption: "Royal Canin, alimento de excelencia",
        imgSrc: "./Images/Royal.png",
        Type: "Perros",
    },
    {
        id: 3,
        name:"Eukanuba",
        price: 10000,
        desciption: "Eukanuba, un clasico en el mercado",
        imgSrc: "./Images/Eukanuba.webp",
        Type: "Perros",
    },
        {
        id: 0,
        name:"Green Dog",
        price: 6900,
        desciption: "Green Dog, alimento 100% Vegetal!",
        imgSrc: "./Images/GD.PNG",
        Type: "Perros",
    },
    {
        id: 1,
        name:"ProPlan",
        price: 7000,
        desciption: "Proplan un clasico en alimentos",
        imgSrc: "./Images/Proplan.png",
        Type: "Perros",
    },
    {
        id: 2,
        name:"Royal Canin",
        price: 12000,
        desciption: "Royal Canin, alimento de excelencia",
        imgSrc: "./Images/Royal.png",
        Type: "Perros",
    },
    {
        id: 3,
        name:"Eukanuba",
        price: 10000,
        desciption: "Eukanuba, un clasico en el mercado",
        imgSrc: "./Images/Eukanuba.webp",
        Type: "Perros",
    },
    {
        id: 4,
        name:"Test gatos",
        price: 10000,
        desciption: "Test gatos filter",
        imgSrc: "./Images/Eukanuba.webp",
        Type: "Gatos",
    },
    {
        id: 5,
        name:"Test otros",
        price: 9999,
        desciption: "Test otros filter",
        imgSrc: "./Images/Proplan.png",
        Type: "Otros",
    },


]