const products = [
    {
        id: 0,
        name:"Green Dog",
        price: 6900,
        desciption: "Green Dog, alimento 100% Vegetal!",
        imgSrc: "./Images/GD.PNG",
    },
    {
        id: 1,
        name:"ProPlan",
        price: 7000,
        desciption: "Proplan un clasico en alimentos",
        imgSrc: "./Images/Proplan.png",
    },
    {
        id: 2,
        name:"Royal Canin",
        price: 12000,
        desciption: "Royal Canin, alimento de excelencia",
        imgSrc: "./Images/Royal.png",
    },
    {
        id: 3,
        name:"Eukanuba",
        price: 10000,
        desciption: "Eukanuba, un clasico en el mercado",
        imgSrc: "./Images/Eukanuba.webp",
    },
    {
        id: 0,
        name:"Green Dog",
        price: 6900,
        desciption: "Green Dog, alimento 100% Vegetal!",
        imgSrc: "./Images/GD.PNG",
    },
    {
        id: 1,
        name:"ProPlan",
        price: 7000,
        desciption: "Proplan un clasico en alimentos",
        imgSrc: "./Images/Proplan.png",
    },
    {
        id: 2,
        name:"Royal Canin",
        price: 12000,
        desciption: "Royal Canin, alimento de excelencia",
        imgSrc: "./Images/Royal.png",
    },
    {
        id: 3,
        name:"Eukanuba",
        price: 10000,
        desciption: "Eukanuba, un clasico en el mercado",
        imgSrc: "./Images/Eukanuba.webp",
    },
    {
        id: 0,
        name:"Green Dog",
        price: 6900,
        desciption: "Green Dog, alimento 100% Vegetal!",
        imgSrc: "./Images/GD.PNG",
    },
    {
        id: 1,
        name:"ProPlan",
        price: 7000,
        desciption: "Proplan un clasico en alimentos",
        imgSrc: "./Images/Proplan.png",
    },
    {
        id: 2,
        name:"Royal Canin",
        price: 12000,
        desciption: "Royal Canin, alimento de excelencia",
        imgSrc: "./Images/Royal.png",
    },
    {
        id: 3,
        name:"Eukanuba",
        price: 10000,
        desciption: "Eukanuba, un clasico en el mercado",
        imgSrc: "./Images/Eukanuba.webp",
    },
]